### PR TITLE
Added declaration of the Reblog API in the header

### PR DESCRIPTION
**Pull request by VIM-Arcange**
This update is in relation relation with the merge #187

### CODE REVIEW

**Comment by VIM-Arcange** [comment]
Code now compile correctly but I get the following error when calling the reblog API from recompiled cli_wallet:

unlocked >>> reblog "arcange" "olegst" "pobediteli-konkursa-zhaka-paganelya-chto-tebya-voskhishaet-v-okruzhayushem-mire-nasekomye" false
```
10 assert_exception: Assert Exception                                                                                               
itr != _by_name.end(): no method with name 'reblog'
...
 th_a  api_connection.hpp:109 call
```

How to add the 'reblog' function to the list of valid methods?

**Comment by VIM-Arcange** [comment]
@kotbegemot Did you saw my last question in the previous comment?

**Comment by kotbegemot** [comment]
Good day @VIM-Arcange .
Updated the code base up to date?

**Comment by VIM-Arcange** [comment]
@kotbegemot 
How to add the 'reblog' function to the list of valid methods?

**Pull request merged**
