### PR TITLE
338 new api

### PR DESCRIPTION
**Pull request by kotbegemot**

### CODE REVIEW

**Comment by t3ran13** [comment]
а что включает в себя новое апи? будет ли обратная совместимость?

**Comment by kotbegemot** [comment]
backwards compatibility will not be. 
Award is for the development of the goals-php library.
https://golos.io/ru--golos/@goloscore/novosti-golos-core-novaya-programma-bounty

**Comment by t3ran13** [comment]
why not? you a move changes with code adaptation, fix it to correct variant? i mean operation numbers for old operations for API have to have the same values. and for new added operations can have other order number

**Comment by kotbegemot** [comment]
The json format is changed to the necessary for sending and receiving data from the chain.
```js
{
	"jsonrpc": "2.0",
	"method": "call",
	"params": ["database_api", "get_dynamic_global_properties", []]
}

```
Operations do not change their order.

**Pull request merged**
