### PR TITLE
Enable PoW mining

### PR DESCRIPTION
**Pull request by primusd**
Check [this link](https://golos.io/ru--golos/@primus/pow-maining-na-golose-umer-da-zdravstvuet-pow-maining-instrukciya-po-mainingu-dlya-tekh-kto-khochet-poprobovat-no-u-nego-ne) for additional info.

### CODE REVIEW

**Comment by VIM-Arcange** [comment]
Why don't we get rid of mining? This is a useless waste of resources.

**Comment by Nemo1369** [comment]
@primusd I would really appreciate if you would stop calling this an "Enablement". It is just a set of dirty-hacky shortcuts to perform PoW computations faster. As far as my experiments show, the trouble with mining is not about shortcuts availability. If these hacks were a trouble, I would have applied them back in July (https://github.com/GolosChain/golos/tree/150-mining-shortcut). Can you confirm these hacks help?

**Comment by primusd** [comment]
@Nemo1369  это не "ускорение" PoW майнинга - без этого "хака" майнинг просто не работает.

**Comment by kotbegemot** [comment]
@Nemo1369 
You need many solution options and it can be added as a softfork.

**Comment by bitfag** [comment]
> Mining is going to be replaced with a special mechanism as far as 19-th version comes. I'ill announce it after we get clear all the stuff about versions 17 & 18.

Please discuss your proposed changes with the community before implementing to avoid wasting resources.

**Comment by bitfag** [comment]
Is it going to be merged into golos-v0.17.0?

**Pull request merged**
